version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache:latest
    container_name: vsp_ledger_ganache
    ports:
      - "8545:8545"
    networks:
      - vsp_ledger_net

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vsp_ledger_web
    ports:
      - "3000:3000"
    networks:
      - vsp_ledger_net

networks:
  vsp_ledger_net:
    driver: bridge
